version: 1.0.0

kafkaConsumer:
  #brokers: localhost:9092;locahost:9091
  brokers: kafka:9092
  groupID: account-group
  topics:
    - account_cons

kafkaProducer:
  #brokers: localhost:9092;locahost:9091
  brokers: kafka:9092
  topics:
    - account_res
    - account_err

jaeger:
  Host: jaeger:6831
  ServiceName: accounts
  LogSpans: false

docs:
  Enable: false
  Prefix: swagger
  Title: Account Service REST API

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug

postgres:
  PostgresqlHost: postgresql_account
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: account
  PostgresqlSSLMode: false
  PgDriver: pgx


cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-totp
  Expire: 3600

metrics:
  Url: 0.0.0.0:7070
  ServiceName: account