version: "3.8"

services:
  #  registration:
  #    container_name: account
  #    build:
  #      context: ./../
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - HTTP_SERVER_PORT=:8081
  #      - JAEGER_HOST=jaeger:6831
  #      - POSTGRES_HOST=postgesql
  #    links:
  #      - postgesql
  #      - jaeger
  #    cap_add:
  #      - SYS_PTRACE
  #    depends_on:
  #      - postgesql
  #    restart: always
  ##    volumes:
  ##      - ./../:/app
  #    networks:
  #      - web_api

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.49
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - web_api

  postgesql:
    image: postgres:14-alpine
    container_name: api_postgesql
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=account
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - web_api

networks:
  web_api:
    driver: bridge