basePath: /api/v1/totp/
definitions:
  models.TOTPEnroll:
    properties:
      base32:
        type: string
      otpath_url:
        type: string
    type: object
info:
  contact:
    name: Rueie
  description: TOTP Service
  license:
    name: MIT License
paths:
  /enroll:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.TOTPEnroll'
      summary: Enroll new user device
      tags:
      - Auth
swagger: "2.0"
