// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: platform/platform.proto

package platform

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Вид деятельности
type ActivityType int32

const (
	ActivityType_UNKNOWNACTTYPE      ActivityType = 0 //  Неизвестный
	ActivityType_AGRICULTUREINDUSTRY ActivityType = 1 //  Сельское хозяйство
	ActivityType_MININGINDUSTRY      ActivityType = 2 //  Добывающая отрасль
	ActivityType_PRODUCTION          ActivityType = 3 //  Произвоство
	ActivityType_CONSTRUCTION        ActivityType = 4 //  Строительство
	ActivityType_TRADING             ActivityType = 5 //  Торговля
	ActivityType_SERVICESECTOR       ActivityType = 6 //  Сфера услуг
	ActivityType_SOCHIALSHPERE       ActivityType = 7 //  Социально-значимые сферы
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "UNKNOWNACTTYPE",
		1: "AGRICULTUREINDUSTRY",
		2: "MININGINDUSTRY",
		3: "PRODUCTION",
		4: "CONSTRUCTION",
		5: "TRADING",
		6: "SERVICESECTOR",
		7: "SOCHIALSHPERE",
	}
	ActivityType_value = map[string]int32{
		"UNKNOWNACTTYPE":      0,
		"AGRICULTUREINDUSTRY": 1,
		"MININGINDUSTRY":      2,
		"PRODUCTION":          3,
		"CONSTRUCTION":        4,
		"TRADING":             5,
		"SERVICESECTOR":       6,
		"SOCHIALSHPERE":       7,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_platform_proto_enumTypes[0].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_platform_platform_proto_enumTypes[0]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{0}
}

// Тип налогообложения
type TaxationType int32

const (
	TaxationType_UNKNOWNTAXTYPE TaxationType = 0 //  Неизвестный
	TaxationType_OSNO           TaxationType = 1 //  ОСНО
	TaxationType_USH            TaxationType = 2 //  УСН
	TaxationType_PSN            TaxationType = 3 //  ПСН
	TaxationType_NPD            TaxationType = 4 //  НПД
	TaxationType_ESXH           TaxationType = 5 //  УСХН
)

// Enum value maps for TaxationType.
var (
	TaxationType_name = map[int32]string{
		0: "UNKNOWNTAXTYPE",
		1: "OSNO",
		2: "USH",
		3: "PSN",
		4: "NPD",
		5: "ESXH",
	}
	TaxationType_value = map[string]int32{
		"UNKNOWNTAXTYPE": 0,
		"OSNO":           1,
		"USH":            2,
		"PSN":            3,
		"NPD":            4,
		"ESXH":           5,
	}
)

func (x TaxationType) Enum() *TaxationType {
	p := new(TaxationType)
	*p = x
	return p
}

func (x TaxationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxationType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_platform_proto_enumTypes[1].Descriptor()
}

func (TaxationType) Type() protoreflect.EnumType {
	return &file_platform_platform_proto_enumTypes[1]
}

func (x TaxationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxationType.Descriptor instead.
func (TaxationType) EnumDescriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{1}
}

// ФИО
type FCs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`             //  Имя
	Surname    string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`       //  Фамилия
	Patronymic string `protobuf:"bytes,3,opt,name=patronymic,proto3" json:"patronymic,omitempty"` //  Отчество
}

func (x *FCs) Reset() {
	*x = FCs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FCs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FCs) ProtoMessage() {}

func (x *FCs) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FCs.ProtoReflect.Descriptor instead.
func (*FCs) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{0}
}

func (x *FCs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FCs) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *FCs) GetPatronymic() string {
	if x != nil {
		return x.Patronymic
	}
	return ""
}

// Паспорт
type Passport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Series             string               `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`                                                   //  Серия
	Number             string               `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`                                                   //  Номер
	Fcs                *FCs                 `protobuf:"bytes,3,opt,name=fcs,proto3" json:"fcs,omitempty"`                                                         //  ФИО
	BirthDate          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`                            //  Дата рождения
	BirthLocation      string               `protobuf:"bytes,5,opt,name=birth_location,json=birthLocation,proto3" json:"birth_location,omitempty"`                //  Место рождения
	PickUpPoint        string               `protobuf:"bytes,6,opt,name=pick_up_point,json=pickUpPoint,proto3" json:"pick_up_point,omitempty"`                    //  Пункт выдачи паспорта
	Authority          uint32               `protobuf:"varint,7,opt,name=authority,proto3" json:"authority,omitempty"`                                            //  Код пункта выдачи
	AuthorityDate      *timestamp.Timestamp `protobuf:"bytes,8,opt,name=authority_date,json=authorityDate,proto3" json:"authority_date,omitempty"`                //  Дата выдачи пасорта
	RegistrationAdress string               `protobuf:"bytes,9,opt,name=registration_adress,json=registrationAdress,proto3" json:"registration_adress,omitempty"` //  Адресс регистрации
}

func (x *Passport) Reset() {
	*x = Passport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_platform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Passport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passport) ProtoMessage() {}

func (x *Passport) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passport.ProtoReflect.Descriptor instead.
func (*Passport) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{1}
}

func (x *Passport) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Passport) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Passport) GetFcs() *FCs {
	if x != nil {
		return x.Fcs
	}
	return nil
}

func (x *Passport) GetBirthDate() *timestamp.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Passport) GetBirthLocation() string {
	if x != nil {
		return x.BirthLocation
	}
	return ""
}

func (x *Passport) GetPickUpPoint() string {
	if x != nil {
		return x.PickUpPoint
	}
	return ""
}

func (x *Passport) GetAuthority() uint32 {
	if x != nil {
		return x.Authority
	}
	return 0
}

func (x *Passport) GetAuthorityDate() *timestamp.Timestamp {
	if x != nil {
		return x.AuthorityDate
	}
	return nil
}

func (x *Passport) GetRegistrationAdress() string {
	if x != nil {
		return x.RegistrationAdress
	}
	return ""
}

// Реквизиты счёта
type AccountDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CulcNumber string `protobuf:"bytes,1,opt,name=culc_number,json=culcNumber,proto3" json:"culc_number,omitempty"` // Расчётный номер
	CorrNumber string `protobuf:"bytes,2,opt,name=corr_number,json=corrNumber,proto3" json:"corr_number,omitempty"` // Корреспондентский номер
	Bic        string `protobuf:"bytes,3,opt,name=bic,proto3" json:"bic,omitempty"`                                 //  БИК
	Cio        string `protobuf:"bytes,4,opt,name=cio,proto3" json:"cio,omitempty"`                                 //  КПП
	Inn        string `protobuf:"bytes,5,opt,name=inn,proto3" json:"inn,omitempty"`                                 //  ИНН
}

func (x *AccountDetails) Reset() {
	*x = AccountDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_platform_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetails) ProtoMessage() {}

func (x *AccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_platform_platform_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetails.ProtoReflect.Descriptor instead.
func (*AccountDetails) Descriptor() ([]byte, []int) {
	return file_platform_platform_proto_rawDescGZIP(), []int{2}
}

func (x *AccountDetails) GetCulcNumber() string {
	if x != nil {
		return x.CulcNumber
	}
	return ""
}

func (x *AccountDetails) GetCorrNumber() string {
	if x != nil {
		return x.CorrNumber
	}
	return ""
}

func (x *AccountDetails) GetBic() string {
	if x != nil {
		return x.Bic
	}
	return ""
}

func (x *AccountDetails) GetCio() string {
	if x != nil {
		return x.Cio
	}
	return ""
}

func (x *AccountDetails) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

var File_platform_platform_proto protoreflect.FileDescriptor

var file_platform_platform_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x03, 0x46, 0x43, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x74,
	0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x61, 0x74, 0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63, 0x22, 0xf3, 0x02, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x03, 0x66, 0x63, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46,
	0x43, 0x73, 0x52, 0x03, 0x66, 0x63, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x69, 0x72, 0x74, 0x68, 0x5f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69, 0x72, 0x74,
	0x68, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x70, 0x69, 0x63,
	0x6b, 0x5f, 0x75, 0x70, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0e, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x2f,
	0x0a, 0x13, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x88, 0x01, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x6c, 0x63, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x6c, 0x63, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x72, 0x72, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x62, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x2a, 0xa4, 0x01, 0x0a, 0x0c, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x41, 0x43, 0x54, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x13, 0x41, 0x47, 0x52, 0x49, 0x43, 0x55, 0x4c, 0x54, 0x55, 0x52, 0x45, 0x49, 0x4e,
	0x44, 0x55, 0x53, 0x54, 0x52, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x49, 0x4e, 0x49,
	0x4e, 0x47, 0x49, 0x4e, 0x44, 0x55, 0x53, 0x54, 0x52, 0x59, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x54, 0x52, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x53, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x06, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x4f, 0x43, 0x48, 0x49, 0x41, 0x4c, 0x53, 0x48, 0x50, 0x45, 0x52, 0x45, 0x10,
	0x07, 0x2a, 0x51, 0x0a, 0x0c, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x54, 0x41, 0x58, 0x54,
	0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x53, 0x4e, 0x4f, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x55, 0x53, 0x48, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x53, 0x4e, 0x10,
	0x03, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x50, 0x44, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x53,
	0x58, 0x48, 0x10, 0x05, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x47, 0x43, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x64, 0x62, 0x6f,
	0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_platform_platform_proto_rawDescOnce sync.Once
	file_platform_platform_proto_rawDescData = file_platform_platform_proto_rawDesc
)

func file_platform_platform_proto_rawDescGZIP() []byte {
	file_platform_platform_proto_rawDescOnce.Do(func() {
		file_platform_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_platform_proto_rawDescData)
	})
	return file_platform_platform_proto_rawDescData
}

var file_platform_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_platform_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_platform_proto_goTypes = []interface{}{
	(ActivityType)(0),           // 0: platform.ActivityType
	(TaxationType)(0),           // 1: platform.TaxationType
	(*FCs)(nil),                 // 2: platform.FCs
	(*Passport)(nil),            // 3: platform.Passport
	(*AccountDetails)(nil),      // 4: platform.AccountDetails
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_platform_platform_proto_depIdxs = []int32{
	2, // 0: platform.Passport.fcs:type_name -> platform.FCs
	5, // 1: platform.Passport.birth_date:type_name -> google.protobuf.Timestamp
	5, // 2: platform.Passport.authority_date:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_platform_platform_proto_init() }
func file_platform_platform_proto_init() {
	if File_platform_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FCs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_platform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Passport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_platform_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_platform_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_platform_proto_goTypes,
		DependencyIndexes: file_platform_platform_proto_depIdxs,
		EnumInfos:         file_platform_platform_proto_enumTypes,
		MessageInfos:      file_platform_platform_proto_msgTypes,
	}.Build()
	File_platform_platform_proto = out.File
	file_platform_platform_proto_rawDesc = nil
	file_platform_platform_proto_goTypes = nil
	file_platform_platform_proto_depIdxs = nil
}
