version: 1.0.0
http-server:
  AppVersion: 1.0.0
  Env: Development
  Port: :8080
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

redis:
  RedisAddr: redis_api_gateway:6379
  RedisPassword: admin
  MaxRetries: 3
  User: admin
  DbId: 0
  DialTimeout: 1
  Timeout: 1

internalServices:
  registration:
    Host: service_registration
    Port: 8080
    Retry: 10
    TimeWaitRetry: 1000
    TimeWaitResponse: 5000
  users:
    Host: service_users
    Port: 8080
    Retry: 1
    TimeWaitRetry: 100
    TimeWaitResponse: 3000
  accounts:
    Host: service_accounts
    Port: 8080
    Retry: 1
    TimeWaitRetry: 100
    TimeWaitResponse: 3000
  notification:
    Host: service_notification
    Port: 8080
    Retry: 1
    TimeWaitRetry: 100
    TimeWaitResponse: 3000

RabbitMQ:
  Host: rabbitmq
  Port: 5672
  User: admin
  Password: admin
  Queue: notification

jaeger:
  Host: jaeger:6831
  ServiceName: api_gateway
  LogSpans: false

docs:
  Enable: false
  Prefix: swagger
  Title: ApiGetway Service REST API

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-gateway
  Expire: 3600

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api-gateway
