package usecase

import "errors"

var (
	ErrorNotEnoughMoneyAmount = errors.New("Not enough money amount!")

	ErrorWrongAccReservedStatus = errors.New("For this operation account has wrong status: reserved!")
	ErrorWrongAccCreatedStatus  = errors.New("For this operation account has wrong status: created!")
	ErrorWrongAccOpenStatus     = errors.New("For this operation account has wrong status: opened!")
	ErrorWrongAccCloseStatus    = errors.New("For this operation account has wrong status: closed!")
	ErrorWrongAccBlockStatus    = errors.New("For this operation account has wrong status: blocked!")

	ErrorAccIsExisting = errors.New("Account for this acc uuid is existing!")
	ErrorNoFoundAcc    = errors.New("No account found!")

	ErrorWrongAccStatus               = errors.New("Wrong account status!")
	ErrorWrongMoneyValue              = errors.New("Wrong money value!")
	ErrorReasonIsExisting             = errors.New("Reason for this acc uuid is existing!")
	ErrorCreateAcc                    = errors.New("accountRepo.CreateAccount")
	ErrorUpdateAccStatus              = errors.New("accountRepo.UpdateAccountStatus")
	ErrorOverflowAmount               = errors.New("Amount overflow!")
	ErrorUpdateAmountValue            = errors.New("accountRepo.UpdateAccountAmount")
	ErrorWrongOwnerLen                = errors.New("Owner has wrong len!")
	ErrorWrongOwner                   = errors.New("Owner cod is not existing")
	ErrorWrongActivityLen             = errors.New("Wrong activity len")
	ErrorWrongActivity                = errors.New("Activity is not existing")
	ErrorWrongCurrencyLen             = errors.New("Wrong currency len")
	ErrorWrongCurrencyValue           = errors.New("Wrong currency value")
	ErrorWrongBICLen                  = errors.New("Wrong BIC length")
	ErrorWrongPaymentSystem           = errors.New("Wrong payment system")
	ErrorWrongAccCountry              = errors.New("Wrong account country")
	ErrorWrongPaymentSystemLen        = errors.New("Wrong payment system len")
	ErrorWrongAccCountryLen           = errors.New("Wrong country len")
	ErrorWrongAccCountryRegionLen     = errors.New("Wrong country region len")
	ErrorWrongAccCountryRegion        = errors.New("Wrong country region")
	ErrorWrongAccMainOfficeLen        = errors.New("Wrong main office len")
	ErrorWrongAccMainOffice           = errors.New("Wrong main office")
	ErrorWrongAccBankNumberLen        = errors.New("Wrong bank number len")
	ErrorWrongAccBankNumber           = errors.New("Wrong bank number")
	ErrorWrongAccCorrNumberLen        = errors.New("Wrong corr number len")
	ErrorWrongAccCorrNumber           = errors.New("Wrong corr number")
	ErrorWrongAccCorrFirstGroupNumber = errors.New("Wrong corr number first group number")
	ErrorWrongAccCorrOwnerLen         = errors.New("Wrong corr number owner len")
	ErrorWrongAccCorrOwner            = errors.New("Wrong corr number owner")
	ErrorWrongAccCorrBankNumber       = errors.New("Wrong corr number bank number")
	ErrorWrongAccKPPLen               = errors.New("Wrong KPP len")
	ErrorWrongAccKPP                  = errors.New("Wrong KPP")
	ErrorWrongCulcNumberLen           = errors.New("Wrong culc number len")
)
