version: 1.0.0
http-server:
  AppVersion: 1.0.0
  Env: Development
  Port: :8080
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

redis:
  RedisAddr: localhost:5500
  RedisPassword: admin
  MaxRetries: 3
  User: admin
  DbId: 0
  DialTimeout: 1
  Timeout: 1

registration:
  Host: localhost
  Port: 8117
  Retry: 5
  TimeWaitRetry: 100
  TimeWaitResponse: 3000

jaeger:
  Host: localhost:6831
  ServiceName: api_gateway
  LogSpans: false

docs:
  Enable: false
  Prefix: swagger
  Title: ApiGetway Service REST API

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-gateway
  Expire: 3600

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api-gateway