// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/GCFactory/dbo-system/service/totp/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Disable mocks base method.
func (m *MockRepository) Disable(ctx context.Context, request models.TOTPRequest) (*models.TOTPBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, request)
	ret0, _ := ret[0].(*models.TOTPBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable indicates an expected call of Disable.
func (mr *MockRepositoryMockRecorder) Disable(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockRepository)(nil).Disable), ctx, request)
}

// Enable mocks base method.
func (m *MockRepository) Enable(ctx context.Context, request models.TOTPRequest) (*models.TOTPBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, request)
	ret0, _ := ret[0].(*models.TOTPBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable indicates an expected call of Enable.
func (mr *MockRepositoryMockRecorder) Enable(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockRepository)(nil).Enable), ctx, request)
}

// Enroll mocks base method.
func (m *MockRepository) Enroll(ctx context.Context, totp models.TOTPConfig) (*models.TOTPEnroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enroll", ctx, totp)
	ret0, _ := ret[0].(*models.TOTPEnroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enroll indicates an expected call of Enroll.
func (mr *MockRepositoryMockRecorder) Enroll(ctx, totp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enroll", reflect.TypeOf((*MockRepository)(nil).Enroll), ctx, totp)
}

// Validate mocks base method.
func (m *MockRepository) Validate(ctx context.Context, request models.TOTPRequest) (*models.TOTPBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, request)
	ret0, _ := ret[0].(*models.TOTPBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockRepositoryMockRecorder) Validate(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockRepository)(nil).Validate), ctx, request)
}

// Verify mocks base method.
func (m *MockRepository) Verify(ctx context.Context, request models.TOTPRequest) (*models.TOTPConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, request)
	ret0, _ := ret[0].(*models.TOTPConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockRepositoryMockRecorder) Verify(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockRepository)(nil).Verify), ctx, request)
}
